CREATE TABLE IF NOT EXISTS LOCATIONS (
   ID           INT(6)          NOT NULL AUTO_INCREMENT, 
   NAME         VARCHAR(250)    NOT NULL, 
   ADDRESS      VARCHAR(250)    NOT NULL,
   DESCRIPTION  VARCHAR(500),
   PHONE_NUMBER VARCHAR(20),
   CREATED_AT   DATETIME,
   PRIMARY KEY (ID)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS COMMENTS (
   ID           INT(6)          NOT NULL AUTO_INCREMENT,
   USERNAME     VARCHAR(250)    NOT NULL,
   BODY         VARCHAR(250)    NOT NULL,
   CREATED_AT   DATETIME,
   LOCATION_ID  INT(6)          NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(ID) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS PARTIES (
   ID           INT(6)          NOT NULL AUTO_INCREMENT,
   NAME         VARCHAR(50)     NOT NULL,
   DESCRIPTION  VARCHAR(500),
   START_AT     DATETIME        NOT NULL,
   CREATED_AT   DATETIME,
   LOCATION_ID  INT(6)          NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(ID) ON DELETE CASCADE    
) ENGINE=InnoDB
