CREATE TABLE IF NOT EXISTS LOCATIONS (
   ID           INT(6)          NOT NULL AUTO_INCREMENT, 
   NAME         VARCHAR(250)    NOT NULL, 
   CREATED_AT   DATETIME,
   PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS COMMENTS (
   ID           INT(6)          NOT NULL AUTO_INCREMENT,
   USERNAME     VARCHAR(25)     NOT NULL,
   BODY         VARCHAR(250)    NOT NULL,
   CREATED_AT   DATETIME,
   LOCATION_ID  INT(6)          NOT NULL,
   PRIMARY KEY (ID),
   FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS(ID)
);
